import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import {QueryClient,QueryClientProvider} from 'react-query';



const inter = Inter({ subsets: ["latin"] });
// const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <QueryClientProvider client={queryClient}>
  <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
       </ClerkProvider>
      // </QueryClientProvider>
  );
}
