import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ReactQueryProviderWrapper from "@/components/providers/reactquery-provider-wrapper";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import SheetProvider from "@/components/providers/sheet-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProviderWrapper>
      <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <SheetProvider />
            <Toaster />
            {children}
          </body>
        </html>
      </ClerkProvider>
    </ReactQueryProviderWrapper>
  );
}
