import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ReactQueryProviderWrapper from "@/components/providers/reactquery-provider-wrapper";
import { Toaster } from "@/components/ui/sonner";


import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// import AccountSheetProvider from "@/components/providers/account-page-sheet-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
 
}>) {
  return (
    <ReactQueryProviderWrapper>
      {/* <ClerkProvider> */}
      <html lang="en">
        <body className={inter.className}>
          {/* <AccountSheetProvider /> */}
          <Toaster />
          {children}

          <ReactQueryDevtools initialIsOpen={false} />
        </body>
      </html>
      {/* </ClerkProvider> */}
    </ReactQueryProviderWrapper>
  );
}
